### ISSUE TITLE
I have many Error when build to Android

### ISSUE THREAD

**Issue by AmirAhmedDarrag** [IBM/unity-sdk-core#29]
![image](https://user-images.githubusercontent.com/20935111/77256783-f9244300-6c78-11ea-8957-a33ddc110aee.png)

**Comment by mamoonraja** [comment]
Hi @AmirAhmedDarrag, Can you please provide info on what version of `Unity`, and what kind of `OS` you are using?

**Comment by AmirAhmedDarrag** [comment]
Hello,

Thank you for your response, I have been solved this problem when upgrading
the unity version from 2018 to 2019

Thank you,

**Comment by mamoonraja** [comment]
Awesome! Thanks for the quick response.
