### ISSUE TITLE
[speech-to-text] Android build issue

### ISSUE THREAD

**Issue by soniahotdogtrio** [IBM/unity-sdk-core#5]
The speech to text is working as expected in the unity window, however I am unable to do an Android build. Here is an image of the error messages:

![ibmsdk](https://user-images.githubusercontent.com/46904708/55749672-8726ff80-5a0f-11e9-97bb-43d6876f0782.PNG)

I have tried creating a new project. These errors appear as soon as I clone the IBM-sdk-core to my Assets folder.

**Comment by mediumTaj** [comment]
This looks like issues with FullSerializer. I don't think we need it anymore so I removed it in https://github.com/IBM/unity-sdk-core/pull/6
